global:
  scrape_interval: 15s 
  evaluation_interval: 15s 

alerting:
  alertmanagers:
    - static_configs:
       - targets:
         - alertmanager:9093

rule_files:
 - "Rules.yml"

scrape_configs:

  - job_name: 'site-monitor'
    metrics_path: /probe
    params:
        module: [http_2xx]
    http_sd_configs:
      - url: http://manager:8000/api/monitor
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.
