apiVersion: v1
data:
  Prometheus.yml: "global:\n  scrape_interval: 15s \n  evaluation_interval: 15s \n\nalerting:\n  alertmanagers:\n    - static_configs:\n       - targets:\n         - alertmanager:9093\n\nrule_files:\n - \"Rules.yml\"\n\nscrape_configs:\n\n  - job_name: 'site-monitor'\n    metrics_path: /probe\n    params:\n        module: [http_2xx]\n    http_sd_configs:\n      - url: http://manager:8000/api/monitor\n    relabel_configs:\n      - source_labels: [__address__]\n        target_label: __param_target\n      - source_labels: [__param_target]\n        target_label: instance\n      - target_label: __address__\n        replacement: blackbox-exporter:9115  # The blackbox exporter's real hostname:port.\n"
kind: ConfigMap
metadata:
  annotations:
    use-subpath: "true"
  labels:
    io.kompose.service: prometheus
  name: prometheus-cm1
