apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: alertmanager
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: alertmanager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: alertmanager
    spec:
      containers:
        - image: prom/alertmanager:main
          name: alertmanager
          ports:
            - containerPort: 9093
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /data
              name: alertmanager-data
            - mountPath: /alertmanager/alertmanager.yml
              name: alertmanager-cm1
              subPath: alertmanager.yml
            - mountPath: /alertmanager/Notification.tmpl
              name: alertmanager-cm2
              subPath: Notification.tmpl
      restartPolicy: Always
      volumes:
        - name: alertmanager-data
          persistentVolumeClaim:
            claimName: alertmanager-data
        - configMap:
            items:
              - key: Alertmanager.yml
                path: alertmanager.yml
            name: alertmanager-cm1
          name: alertmanager-cm1
        - configMap:
            items:
              - key: Notification.tmpl
                path: Notification.tmpl
            name: alertmanager-cm2
          name: alertmanager-cm2
