apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: blackbox-exporter
  name: blackbox-exporter
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: blackbox-exporter
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: blackbox-exporter
    spec:
      containers:
        - args:
            - --config.file=/config/blackbox.yml
          image: quay.io/prometheus/blackbox-exporter:latest
          name: blackbox-exporter
          ports:
            - containerPort: 9115
              protocol: TCP
          volumeMounts:
            - mountPath: /config/blackbox.yml
              name: blackbox-exporter-cm0
              subPath: blackbox.yml
      restartPolicy: Always
      volumes:
        - configMap:
            items:
              - key: Blackbox.yml
                path: blackbox.yml
            name: blackbox-exporter-cm0
          name: blackbox-exporter-cm0
