apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: grafana
  name: grafana
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: grafana
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: grafana
    spec:
      containers:
        - image: grafana/grafana:latest
          name: grafana
          ports:
            - containerPort: 3000
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data
            - mountPath: /etc/grafana/provisioning/datasources/datasources.yml
              name: grafana-cm1
              subPath: datasources.yml
            - mountPath: /etc/grafana/provisioning/dashboards/dashboards.yml
              name: grafana-cm2
              subPath: dashboards.yml
            - mountPath: /etc/grafana/provisioning/dashboards/BlackBoxExporterDashboardDetailed.json
              name: grafana-cm3
              subPath: BlackBoxExporterDashboardDetailed.json
            - mountPath: /etc/grafana/provisioning/dashboards/BlackBoxExporterDashboardSimple.json
              name: grafana-cm4
              subPath: BlackBoxExporterDashboardSimple.json
      restartPolicy: Always
      volumes:
        - name: grafana-data
          persistentVolumeClaim:
            claimName: grafana-data
        - configMap:
            items:
              - key: DataSources.yml
                path: datasources.yml
            name: grafana-cm1
          name: grafana-cm1
        - configMap:
            items:
              - key: Dashboards.yml
                path: dashboards.yml
            name: grafana-cm2
          name: grafana-cm2
        - configMap:
            items:
              - key: BlackBoxExporterDashboardDetailed.json
                path: BlackBoxExporterDashboardDetailed.json
            name: grafana-cm3
          name: grafana-cm3
        - configMap:
            items:
              - key: BlackBoxExporterDashboardSimple.json
                path: BlackBoxExporterDashboardSimple.json
            name: grafana-cm4
          name: grafana-cm4
