apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.34.0 (HEAD)
  labels:
    io.kompose.service: manager
  name: manager
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: manager
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.34.0 (HEAD)
      labels:
        io.kompose.service: manager
    spec:
      containers:
        - env:
            - name: DB_CONNECTION
              value: sqlite
            - name: DB_DATABASE
              value: /var/www/database/database.sqlite
          image: ggmartinez/blackbox-exporter-discovery-manager
          livenessProbe:
            exec:
              command:
                - curl --fail http://localhost:8000 || exit 1
            failureThreshold: 5
            periodSeconds: 10
            timeoutSeconds: 5
          name: manager
          ports:
            - containerPort: 8000
              protocol: TCP
          tty: true
          volumeMounts:
            - mountPath: /var/www/database
              name: manager-data
      restartPolicy: Always
      volumes:
        - name: manager-data
          persistentVolumeClaim:
            claimName: manager-data
