{
 "title": "Blackbox Exporter Detailed",
 "tags": [
  "blackbox",
  "prometheus"
 ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   {
    "name": "job",
    "label": "Job",
    "query": "label_values(probe_success, job)"
   },
   {
    "name": "instance",
    "label": "URL",
    "query": "label_values(probe_success{job=~\"$job\"}, instance)"
   },
   {
    "name": "category",
    "label": "Category",
    "query": {
     "query": "label_values(probe_success{job=~\"$job\"},category)"
    }
   }
  ]
 },
 "panels": [
  { "title": "HTTP Status", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "HTTP Probe Overview",
   "type": "table",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "probe_success{job=~\"$job\", instance=~\"$instance\", category=~\"$category\"}"
    },
    {
     "expr": "probe_http_ssl{job=~\"$job\", instance=~\"$instance\", category=~\"$category\"} > 0"
    },
    {
     "expr": "(probe_ssl_earliest_cert_expiry{job=~\"$job\", instance=~\"$instance\", category=~\"$category\"} - time()) / 3600 / 24"
    },
    {
     "expr": "probe_http_status_code{job=~\"$job\", instance=~\"$instance\", category=~\"$category\"} > 0"
    },
    {
     "expr": "avg_over_time(probe_duration_seconds{job=~\"$job\", instance=~\"$instance\", category=~\"$category\"}[1m])"
    },
    {
     "expr": "probe_tls_version_info{job=~\"$job\", instance=~\"$instance\", category=~\"$category\"}"
    },
    {
     "expr": "avg_over_time(probe_dns_lookup_time_seconds{job=~\"$job\", instance=~\"$instance\", category=~\"$category\"}[1m])"
    }
   ]
  },
  { "title": "Probe Duration", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 } },
  {
   "title": "HTTP Probe Duration",
   "type": "timeseries",
   "description": "Returns how long the probe took to complete in seconds",
   "gridPos": { "h": 9, "w": 24, "x": 0, "y": 11 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "sum(probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\",category=~\"$category\"}) by (instance)",
     "legendFormat": "{{ instance }}"
    }
   ]
  },
  {
   "title": "$instance",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 20 },
   "repeat": "instance",
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "HTTP Probe Phases Duration",
     "type": "timeseries",
     "description": "Duration of http request by phase, summed over all redirects",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "s" } },
     "targets": [
      {
       "expr": "probe_http_duration_seconds{job=~\"$job\", instance=~\"$instance\"}",
       "legendFormat": "{{ phase }}"
      }
     ]
    }
   ]
  }
 ]
}